OKX_API_KEY = "f74131b4-a111-4ee4-8e9d-e5e52d7f395f"
OKX_SECRET_KEY = "BD9FDEDF622C605F94AAB91FE8846B7F"
OKX_PASSPHRASE = "AbcD@1234"
TV_WEBHOOK_URL = ""
WEBHOOK_URL = ""
IB_HOST = "127.0.0.1"
IB_PORT = 4001
