# OKX API Keys
# live 实盘
OKX_LIVE_API_KEY = "f74131b4-a111-4ee4-8e9d-e5e52d7f395f"
OKX_LIVE_SECRET_KEY = "BD9FDEDF622C605F94AAB91FE8846B7F"
OKX_LIVE_PASSPHRASE = "AbcD@1234"

# sim 模拟盘
OKX_SIM_API_KEY = "7c1d51b0-0104-476c-90db-c6dff1f0b090"
OKX_SIM_SECRET_KEY = "AF8EB679F8AA4CE9A38C5069CB0737A7"
OKX_SIM_PASSPHRASE = "AbcD@1234"

TV_WEBHOOK_URL = ""
WEBHOOK_URL = ""
IB_HOST = "127.0.0.1"
IB_PORT = 4001
