# OKX API 配置
# 密钥从环境变量读取，不要直接写在文件中

okx:
  # 交易模式: 1=实盘, 2=模拟盘
  flag: "2"
  
  live:
    - apikey : "f74131b4-a111-4ee4-8e9d-e5e52d7f395f"
    - secretkey : "BD9FDEDF622C605F94AAB91FE8846B7F"
    - passphrase : "AbcD@1234“

  sim:
    - apikey : "7c1d51b0-0104-476c-90db-c6dff1f0b090"
    - secretkey : "AF8EB679F8AA4CE9A38C5069CB0737A7"
    - passphrase : "AbcD@1234“

  # 交易对配置
  pairs:
    - symbol: "DOGE-USDT"
      min_size: 1
    - symbol: "ETH-USDT"
      min_size: 10
    - symbol: "BTC-USDT"
      min_size: 10


